### ISSUE TITLE
Will HPC move to newer languages?

### ISSUE THREAD

**Issue by impredicative** [VictorEijkhout/TheArtOfHPC_vol1_scientificcomputing#3]
Thanks for the incredible work. Will HPC ever move to a newer stack of Python+Rust or Julia or Unison, etc.? Some of us fear memory leaks in C++ that creep up inevitably.

**Comment by VictorEijkhout** [comment]
Python is a great language for wrapping libraries that are written in C or C++. See for instance Fenics and most libraries in computational biology: C++ under the hood, python as user interface.

Rust: while I have zero experience, I'm guessing that Rust is great as a system language, not as an HPC language. In HPC everything is shared mutable state, so you'd have to run your Rust code in a way that negates all the purported advantages.

Julia: if I had more time I'd look into it. I think the problem is interfacing to millions of existing C/C++/Fortran scientific libraries.

Unison: never heard of it.

Memory leaks: if you write modern C++ you are perfectly safe. Abandon all C-style pointers and use standard containers.
